PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS utlån;
DROP TABLE IF EXISTS låner;
DROP TABLE IF EXISTS eksemplar;
DROP TABLE IF EXISTS bok;

CREATE TABLE bok (
  ISBN TEXT PRIMARY KEY,
  Tittel TEXT NOT NULL,
  Forfatter TEXT NOT NULL,
  Forlag TEXT,
  UtgittÅr INTEGER,
  AntallSider INTEGER CHECK (AntallSider >= 0)
);

CREATE TABLE eksemplar (
  ISBN TEXT NOT NULL,
  EksNr INTEGER NOT NULL,
  PRIMARY KEY (ISBN, EksNr),
  FOREIGN KEY (ISBN) REFERENCES bok(ISBN)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE låner (
  LNr INTEGER PRIMARY KEY,
  Fornavn TEXT NOT NULL,
  Etternavn TEXT NOT NULL,
  Adresse TEXT NOT NULL
);

CREATE TABLE utlån (
  UtlånsNr INTEGER PRIMARY KEY,
  LNr INTEGER NOT NULL,
  ISBN TEXT NOT NULL,
  EksNr INTEGER NOT NULL,
  Utlånsdato TEXT NOT NULL,
  Levert INTEGER NOT NULL CHECK (Levert IN (0,1)),
  FOREIGN KEY (LNr) REFERENCES låner(LNr)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ISBN, EksNr) REFERENCES eksemplar(ISBN, EksNr)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
